## USB port
port: /dev/ttyUSB0

##### Calibration ####
### accelerometer
accel_x_min: -275.0
accel_x_max: 254.0
accel_y_min: -257.0
accel_y_max: 267.0
accel_z_min: -275.0
accel_z_max: 245.0

### magnetometer
# standard calibration
#magn_x_min: -600.0
#magn_x_max: 600.0
#magn_y_min: -600.0
#magn_y_max: 600.0
#magn_z_min: -600.0
#magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [142.415, -58.8213, -117.699]
magn_ellipsoid_transform: [[0.934490, -0.0132499, 0.0163636], [-0.0132499, 0.968349, 0.00775687], [0.0163636, 0.00775687, 0.995230]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -36.22
gyro_average_offset_y: 36.83
gyro_average_offset_z: -33.17
