
# erpm (electrical rpm) = 4422 * speed (meters / second) + 60
speed_to_erpm_gain: 5100.0
speed_to_erpm_offset: 0.0

# servo value (0 to 1) =  -0.917 * steering angle (radians) + 0.5
steering_angle_to_servo_gain: -0.917
steering_angle_to_servo_offset: 0.5

# publish odom to base link tf
vesc_to_odom/publish_tf: true

# car wheelbase is about 33cm (distance between axles)
wheelbase: .33

vesc_driver:
  port: /dev/ttyACM0
  duty_cycle_min: 0.0
  duty_cycle_max: 0.0
  current_min: 0.0
  current_max: 0.0
  brake_min: 0.0
  brake_max: 0.0
  speed_min: -9000
  speed_max: 20000
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.15
  servo_max: 0.85
